services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    container_name: keycloak-airship
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_FEATURES: preview,scripts
      KC_LOG_FORMAT: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"
      KC_LOG_LEVEL: "INFO,org.hibernate:INFO,com.cloudiam:DEBUG,org.keycloak.authentication:DEBUG"
      # To disable the Airship provider, set this to 'default'
      KC_SPI_EMAIL_SENDER_PROVIDER: ${KC_SPI_EMAIL_SENDER_PROVIDER}

      # Airship and email configuration
      AIRSHIP_EMAIL_SENDER: "${AIRSHIP_EMAIL_SENDER}"
      AIRSHIP_ENDPOINT: "${AIRSHIP_ENDPOINT}"
      AIRSHIP_APP_KEY: "${AIRSHIP_APP_KEY}"
      AIRSHIP_ACCESS_TOKEN: "${AIRSHIP_APP_TOKEN}"
      AIRSHIP_HEADER: "${AIRSHIP_HEADER}"
      AIRSHIP_DOMAIN: "${AIRSHIP_DOMAIN}"
      AIRSHIP_EMAIL_SENDER_NAME: "${AIRSHIP_EMAIL_SENDER_NAME}"
      AIRSHIP_EMAIL_REPLY_TO: "${AIRSHIP_EMAIL_REPLY_TO}"

    command:
      - "--verbose"
      - "start-dev"
    ports:
      - "8080:8080"
    volumes:
      - ./target/airship-provider-1.0.0-SNAPSHOT.jar:/opt/keycloak/providers/airship-provider-1.0.0.jar:z
    depends_on:
      - keycloak-db
    networks:
      - keycloak-airship-provider

  keycloak-db:
    image: postgres:16
    networks:
      - keycloak-airship-provider
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

  smtp:
    image: mailhog/mailhog:latest
    networks:
      - keycloak-airship-provider
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres_data:
    driver: local

networks:
  keycloak-airship-provider:
    name: keycloak-airship-provider
