services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0.6
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://keycloak-db:5432/keycloak
      KC_DB_USERNAME: admin
      KC_FEATURES: preview,scripts
      KC_LOG_FORMAT: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n"
      KC_LOG_LEVEL: "INFO,org.hibernate:INFO,com.cloudiam:DEBUG,org.keycloak.authentication:DEBUG"
      SMTP_HOST: "smtp"
      SMTP_PORT: "1025"

      # Airship and email configuration
      AIRSHIP_EMAIL_SENDER: "arte-trials@test.fr"
      AIRSHIP_ENDPOINT: "/api/create-and-send"
      AIRSHIP_APP_KEY: ""  # Add your Airship API key here
      AIRSHIP_ACCESS_TOKEN: ""  # Add your Airship access token here
      AIRSHIP_HEADER: "vnd.urbanairship+json"
      AIRSHIP_DOMAIN: "https://go.airship.eu"

    command:
      - "start-dev"
    ports:
      - "8080:8080"
    depends_on:
      - keycloak-db
    networks:
      - keycloak-airship-provider

  keycloak-db:
    image: postgres:16
    networks:
      - keycloak-airship-provider
    ports:
      - "5432:5432"
    volumes:
      - x_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password

volumes:
  x_postgres_data:
    driver: local

networks:
  keycloak-airship-provider:
